# Generated by Django 4.1 on 2022-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True)),
                ('skype_url', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
        ),
    ]
