# Generated by Django 4.1 on 2022-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_name_customer_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last',
            new_name='last_name',
        ),
    ]
