# Generated by Django 4.1 on 2022-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_industry_rename_notes_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='industry',
            new_name='name',
        ),
    ]
