# Generated by Django 4.1 on 2022-09-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_type', to='crm.industry'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_type', to='crm.status'),
        ),
    ]
