# Generated by Django 4.1 on 2022-09-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_alter_customer_industry_alter_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('file_uplaod', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comapany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
