# Generated by Django 4.1 on 2022-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_email',
            old_name='comapany',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='customer_email',
            name='file_uplaod',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
