# Generated by Django 4.1 on 2022-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_customer_email_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_email',
            old_name='file_uplaod',
            new_name='file_upload',
        ),
    ]
