# Generated by Django 4.1 on 2022-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_contact_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='land_phone_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
