# Generated by Django 4.1 on 2022-10-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='postion',
            new_name='position',
        ),
    ]
