# Generated by Django 4.1 on 2022-10-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_note_writer_alter_note_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
    ]
