# Generated by Django 4.1 on 2022-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Prospect', 'Prospect'), ('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended')], default='Prospect', max_length=100, null=True),
        ),
    ]
