# Generated by Django 4.1 on 2022-09-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_profile_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default-profile.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
