# Generated by Django 4.1 on 2022-10-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_currency_product_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uniqueID',
            new_name='uniqueId',
        ),
    ]
