# Generated by Django 4.1 on 2022-10-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_invoice_date_created_invoice_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_date',
        ),
    ]
