# Generated by Django 4.1 on 2022-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_invoice_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_products',
            name='product',
        ),
        migrations.AddField(
            model_name='customer_products',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
