# Generated by Django 4.1 on 2022-10-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.product'),
        ),
    ]
