# Generated by Django 4.1 on 2022-10-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_price',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
