# Generated by Django 4.1 on 2022-10-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_invoice_discount_presentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_products',
            old_name='customer',
            new_name='customerid',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_presentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
