# Generated by Django 4.1 on 2022-10-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_note_options'),
        ('products', '0017_rename_customer_customer_products_customerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('DZD', 'DZD')], default='DZD', max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer_products',
        ),
        migrations.AddField(
            model_name='customer_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
