# Generated by Django 4.1 on 2022-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_customer_product_alter_product_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_product',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_product',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='time_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
