# Generated by Django 4.1 on 2022-10-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_invoice_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_product',
            name='invoiceid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.invoice'),
        ),
    ]
