# Generated by Django 4.1 on 2022-10-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_customer_product_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_product',
            name='invoiceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.invoice'),
        ),
    ]
