# Generated by Django 4.1 on 2022-10-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_customer_product_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.product'),
        ),
    ]
